# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
new_li = []
while True:
    if len(li) == 1:
        break

    mini = min(li)
    ind = li.index(mini)
    first = li[0]
    li[0] = li[ind]
    li[ind] = first
    print(*new_li, *li)
    new_li.append(li[0])
    li = li[1:]