# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

t = int(input())
for _ in range(t):
    n = int(input())
    dp = [0] * (n + 1)
    if n >= 1:
        dp[1] = 1
    if n >= 2:
        dp[2] = 1
    if n >= 3:
        dp[3] = 1
    if n >= 4:
        dp[4] = 2
    if n >= 5:
        dp[5] = 2
    if n >= 6:
        dp[6] = 3
    if n >= 7:
        dp[7] = 4
    if n >= 8:
        dp[8] = 5
    for i in range(9, n + 1):
        dp[i] = dp[i - 1] + dp[i - 5]
    print(dp[n])