# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import math
n = int(input())
li = list(map(int, input().split()))

cd = math.gcd(*li)
cm = math.lcm(*li)
print(cd, cm)

#연필공장(정올 사이트)
import math
p, v, k = map(int, input().split())
a, b, c, d = 0, 0, 0, 0

cm = math.lcm(p + 1, v + 1)

b = k // cm
c = k // (v  + 1) - b
d = k // (p + 1) - b
a = k - b - c - d

print(a, b, c, d)