# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, k = map(int, input().split())
li = []
dp = [0] * (k + 1)
for _ in range(n):
    li.append(int(input()))

for i in range(len(li)):
    for j in range(1, len(dp)):
        if j % li[i] == 0:
            dp[j] += 1