# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a = int(input())
b = int(input())

b = str(b)
ans1 = a * int(b[2])
ans2 = a * int(b[1])
ans3 = a * int(b[0])

b = int(b)

ans4 = a * b

print(ans1)
print(ans2)
print(ans3)
print(ans4)