# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
dp = [1] * n
for i in range(n):
    for j in range(i):
        if li[j] > li[i]:
            dp[i] = max(dp[i], dp[j] + 1)

print(max(dp))