# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, t = map(int, input().split())
dish = [i for i in range(1, n + 1)]
wash = []
dry = []
dish = dish[::-1]
for _ in range(t):
    c, d = map(int, input().split())
    if c == 1:
        for i in range(d):
            a = dish.pop()
            wash.append(a)
    if c == 2:
        for i in range(d):
            b = wash.pop()
            dry.append(b)

for i in dry[::-1]:
    print(i)