# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

t = int(input())
dp = [[0] * 2 for _ in range(41)]
dp[0] = [1, 0]
dp[1] = [0, 1]
dp[2] = [1, 1]
for i in range(3, 41):
    dp[i][0] = dp[i - 1][0] + dp[i - 2][0]
    dp[i][1] = dp[i - 1][1] + dp[i - 2][1]

for _ in range(t):
    n = int(input())
    a, b = dp[n]
    print(a, b)