# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
ans = 1

def fac(x):
    global ans
    if x == n:
        ans *= x
        if x == 1:
            print('1! = 1')
        else:
            print(f'{x}! = {x} * {x - 1}!')
        return
    ans *= x
    fac(x + 1)
    if x == 1:
        print('1! = 1')
    else:
        print(f'{x}! = {x} * {x - 1}!')

if n >= 1:
    fac(1)

print(ans)