# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

t = int(input())
k = int(input())
cnt = 0
li = []
dp = []
cost_dp = []
total_count = 0
ans = 0

for _ in range(k):
    a, b = map(int, input().split())
    total_count += b
    li_2 = [0] * (b + 1)
    dp.append(li_2)
    li.append([a, b])

for i in range(len(li)):
    for j in range(li[i][1] + 1):
        dp[i][j] = li[i][0] * j

print(dp) #모든 금액이 존재하는 dp 테이블을 만들기 위한 dp 테이블을 만듦