# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, k = map(int, input().split())
money = []
cnt = 0
for _ in range(n):
    money.append(int(input()))

for i in range(len(money)):
    if money[i] > k:
        money = money[:i]
        break

money = money[::-1]
for i in money:
    if k // i > 0:
        cnt += int(k // i)
        k = int(k % i)