# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, m = map(int, input().split())
val = [0 for i in range(n)]
li = []

def dice(step):
    global li
    if step >= n:
        if m == 1:
            print(*val)
            return
        if m == 2:
            print(*val)
            return

        if m == 3:
            flag2 = 0
            for i in val:
                if val.count(i) >= 2:
                    flag2 = 1
                    break
            if flag2 == 1:
                return
            else:
                print(*val)
                return

    if m == 2 and step >= 1:
        for i in range(val[step - 1], 7):
            val[step] = i
            dice(step + 1)
    else:
        for i in range(1, 7):
            val[step] = i
            dice(step + 1)

dice(0)