# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

graph = []
flag = 0

def check(num, i, j, c, r):
    cnt = 0
    for k in range(1, 18):
        if i + c * k < 0 or i + c * k >= 19 or j + r * k < 0 or j + r * k >= 19:
            break
        elif graph[i + c * k][j + r * k] == num:
            cnt += 1
        else:
            break
    return cnt

for i in range(19):
    graph.append(list(map(int, input().split())))

c = [-1, 0, 1, 1]
r = [1, 1, 1, 0]

for i in range(19):
    for j in range(19):
        if graph[i][j] != 0:
            num = graph[i][j]
            for k in range(4):
                if i - c[k] >= 0 and i - c[k] < 19 and j - r[k] >= 0 and j - r[k] < 19:
                    if graph[i - c[k]][j - r[k]] == num:
                        continue
                if check(num, i, j, c[k], r[k]) == 4:
                    print(num)
                    print(i + 1, j + 1)
                    flag += 1

if flag == 0:
    print(0)