# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys
m = int(sys.stdin.readline())
s = set()
for _ in range(m):
    li = list(sys.stdin.readline().split())
    if len(li) == 2:
        cal, num = li
        cal = str(cal)
        num = int(num)
        if cal == 'add':
            if num not in s:
                s.add(num)
            else:
                continue
        elif cal == 'remove':
            if num in s:
                s.remove(num)
            else:
                continue
        elif cal == 'check':
            if num in s:
                print(1)
            else:
                print(0)
        elif cal == 'toggle':
            if num in s:
                s.remove(num)
            else:
                s.add(num)
    elif len(li) == 1:
        cal = li[0]
        cal = str(cal)
        if cal == 'all':
            s = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
        elif cal == 'empty':
            s = set()