# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

num = list(map(int, input().split()))
num = num[1:]
li = [0 for _ in range(6)]
num.sort()

def lotto(step, idx):
    if step == 6:
        print(*li)
        return
    for i in range(idx, len(num)):
        li[step] = num[i]
        lotto(step + 1, i + 1)

lotto(0, 0)