# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
m = int(input())
s = input()
p = 'IOI'
cnt = 0

for _ in range(n - 1):
    p += 'OI'

for i in range(len(s) - len(p) + 1):
    if p in s[i : i + len(p)]:
        cnt += 1

print(cnt)