# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

st = input()
ans = 0
stick = 0

for i in range(len(st)):
    if st[i] == '(':
        stick += 1 #막대기로 간주
    elif st[i] == ')':
        if st[i - 1] == '(':
            stick -= 1
            ans += stick
        else:
            stick -= 1
            ans += 1

print(ans)