# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = str(input())
li = []
i = 0
cnt = 0

if len(n) == 1:
    print(1)

else:
    while True:
        li.append(int(n[i : i + 2]))
        if len(n) <= i + 2:
            break
        i += 1

    if li[0] <= 34:
        cnt += 2
    else:
        cnt += 1

    for i in li[1:]:
        if i <= 34:
            cnt *= 2
        else:
            cnt += 1
    print(li)
    print(cnt)