# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
gcd_li = []

def gcd(x, y):
    if x % y == 0:
        return y
    return gcd(y, x % y)

def lcm(x, y):
    return x // gcd(x, y) * y

cd = 0
cm = 1

for i in li:
    cd = gcd(cd, i)
    cm = lcm(cm, i)
print(cd, cm)