# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

graph = []
ans = 0
flag = 0

def bingo():
    bingo = 0
    for i in range(5):
        cnt_r = 0
        cnt_c = 0
        cnt_rl = 0
        cnt_lr = 0
        for j in range(5):
            if graph[i][j] == True:
                cnt_r += 1
            if graph[j][i] == True:
                cnt_c += 1
        if cnt_r == 5:
            bingo += 1
        if cnt_c == 5:
            bingo += 1 #가로, 세로 빙고

    for i in range(5):
        if graph[i][i] == True:
            cnt_lr += 1
        if graph[i][4 - i] == True:
            cnt_rl += 1

    if cnt_lr == 5:
        bingo += 1
    if cnt_rl == 5:
        bingo += 1 #대각선 빙고

    return bingo

for _ in range(5):
    graph.append(list(map(int, input().split())))

for _ in range(5):
    user = list(map(int, input().split()))
    for i in user:
        ans += 1
        for j in range(len(graph)):
            for k in range(len(graph[j])):
                if graph[j][k] == i:
                    graph[j][k] = True
                if bingo() >= 3:
                    print(ans)
                    flag = 1
                    break
            if flag == 1:
                flag += 1
                break
        if flag == 2:
            flag += 1
            break
    if flag == 3:
        break