# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, m = map(int, input().split())
li = list(map(int, input().split()))
dp = [0] * (n + 1) #n까지의 합을 저장하는 DP 테이블 만듦

for i in range(1, len(dp)):
    dp[i] = dp[i - 1] + li[i - 1]

for i in range(m):
    a, b = map(int, input().split())
    print(dp[b] - dp[a - 1])

#백준 2011번(DP 골드5)
sc = input() # 수를 하나씩 저장
n = len(sc)

# dp 배열의 크기는 n+1로 설정, dp[0]은 빈 문자열에 대한 경우의 수로 1
dp = [0] * (n + 1)

# 처음 입력이 '0'으로 시작하면 해석 불가
if sc[0] == '0':
    print(0)
else:
    dp[0] = 1  # 점화식을 위해 dp[0] = 1로 설정
    dp[1] = 1  # 첫 번째 문자 해석

    for i in range(2, n + 1):
        one = int(sc[i - 1:i])
        two = int(sc[i - 2:i])

        if 1 <= one <= 9:
            dp[i] += dp[i - 1]

        if 10 <= two <= 26:
            dp[i] += dp[i - 2]

        dp[i] %= 1000000

    print(dp[n])