# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a = input()
leng = 0

if len(a) > 0:
    leng += 10

for i in range(len(a) - 1):
    if a[i] == a[i + 1]:
        leng += 5
    else:
        leng += 10

print(leng)