# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys
sys.setrecursionlimit(10000)

n, m, v = map(int, input().split())
info = []
visit = []
for _ in range(m):
    info.append(list(map(int, input().split())))

def dfs(v, visit, info):
    visit_can = []
    val = []
    for i in info:
        if i[0] == v:
            visit_can.append(i[1])
            val.append(i)
        elif i[1] == v:
            visit_can.append(i[0])
            val.append(i)

    v = min(visit_can)
    info.remove(val[visit_can.index(v)])
    visit.append(v)
    visit_can = []
    if len(info) == 0:
        return visit
    else:
        return dfs(v, visit, info)

print(dfs(v, visit, info))