# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())

for i in range(n):
    m = int(input())
    dic = {}
    dic_clo = {}
    cnt = 0
    multiply = 1

    for i in range(m):
        cloth, place = map(str, input().split())
        dic[cloth] = place

    for i in dic:
        dic_clo[dic.get(i)] = 0

    for i in dic:
        dic_clo[dic.get(i)] += 1

    if len(dic_clo) == 1:
        cnt += len(dic)
        print(cnt)
        continue

    else:
        for i in dic_clo:
            multiply *= dic_clo.get(i) + 1
        cnt += multiply - 1
        print(cnt)