# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys
sys.setrecursionlimit(10000)

t = int(input())

dirR = [0, 0, -1, 1]
dirC = [-1, 1, 0, 0]

def dfs(x, y):
    global visited
    visited[y][x] = True
    for i in range(4):
        newX = x + dirR[i]
        newY = y + dirC[i]
        if 0 <= newX < m and 0 <= newY < n: #indexError를 방지하기 위해서 범위 내의 값인지 확인
            if graph[newY][newX] and not visited[newY][newX]: #그래프가 True이고 방문을 안 했으면 다시 dfs 호출
                dfs(newX, newY)

for _ in range(t):
    m, n, k = map(int, input().split())
    graph = [[False] * m for _ in range(n)]
    visited = [[False] * m for _ in range(n)]

    for _ in range(k):
        x, y = map(int, input().split())
        graph[y][x] = True

    ans = 0
    for i in range(m):
        for j in range(n):
            if graph[j][i] and (not visited[j][i]): #2차원 배열은 [행][열](= y, x) 순서로 접근
                dfs(i, j) #i가 열, j가 행
                ans += 1
    print(ans)