# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
n_li = list(map(str, input().split()))
m = int(input())
m_li = list(map(str, input().split()))

dic = {}
for i in n_li:
    dic[i] = 0

for i in n_li:
    dic[i] += 1

for i in m_li:
    if dic.get(i) == None:
        print(0)
    else:
        print(dic.get(i))