# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import math
li = []

n = int(input())
for i in range(1, math.isqrt(n) + 1):
    if n % i == 0:
        print(i, end = ' ')
        if i == int(n / i):
            continue
        li.append(int(n / i))

for i in range(1, len(li) + 1):
    print(li[-i], end = ' ')