# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
dis = []
cnt = 1
st = 0

for _ in range(n):
    dis.append(list(map(int, input().split())))

dis.sort(key = lambda x: (x[1], x[0])) #이차원 리스트 정렬법 이처럼 쓰면 x[1]을 기준으로 오름차순 정렬하고, x[0]을 기준으로 두 번째 오름차순 정렬(사전순)

for i in range(1, len(dis)):
    if dis[i][0] >= dis[st][1]:
        cnt += 1
        st = i

print(cnt)