# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a = input()
b = input()
dic = {}
ans = ''
for i in range(97, 123):
    dic[chr(i)] = a[i - 97]

for i in b:
    if i == ' ':
        ans += ' '
    elif i.isupper():
        ans += dic.get(i.lower()).upper()
    else:
        ans += str(dic.get(i))
print(ans)