# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
dp = [0] * n
for i in range(n):
    dp[i] = max(li[i], li[i] + dp[i - 1])

print(max(dp))