# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, m = map(int, input().split())

class matrix:
    def __init__(self, n):
        self.li = []
        self.n = n
        for i in range(n):
            self.li.append(list(map(int, input().split())))

    def __mul__(self, other):
        ans = [[0 for _ in range(k)] for _ in range(n)]
        for b in range(n):
            for c in range(k):
                val = 0
                for a in range(m):
                    val += self.li[b][a] * other.li[a][c]
                ans[b][c] = val
        return ans

A = matrix(n)

m, k = map(int, input().split())
B = matrix(m)
ans = A * B

for i in range(len(ans)):
    print(*ans[i])