# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys
n = int(input())
m = int(input())
s = input()
place = 0
count = 0
ans = 0

while place <= len(s) - 2:
    if s[place : place + 3] == 'IOI':
        count += 1
        place += 2
        if count == n:
            ans += 1
            count -= 1
    else:
        place += 1
        count = 0

print(ans)