# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, m = map(int, input().split())
dic = {}

for i in range(n):
    site, pw = map(str, input().split())
    dic[site] = pw

for i in range(m):
    print(dic.get(input()))