# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

t = int(input())

for _ in range(t):
    a = input()
    stack = []
    is_valid = True

    for char in a:
        if char == '(':
            stack.append(char)
        elif char == ')':
            if stack:
                stack.pop()
            else:
                is_valid = False
                break

    if is_valid and not stack:
        print('YES')
    else:
        print('NO')