# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
a = list(map(int, input().split()))
cnt = 0

for i in range(1, n):
    value = a[i]
    while i > 0 and a[i-1] > value:
        a[i] = a[i - 1]
        cnt += 1
        i -= 1
    a[i] = value

print(cnt)