# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a, b = map(int, input().split())

def gcd(x, y):
    if x % y == 0:
        return y
    return gcd(y, x % y)

def lcm(x, y):
    return int(x / gcd(x, y)) * y

print(gcd(a, b))
print(lcm(a, b))