# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a, b = map(int, input().split())
c, d = map(int, input().split())
li_1 = []
li_2 = []
li_dup = [] #중복되는 소수 저장

def prime(x):
    for i in range(2, x):
        if x % i == 0:
            return False
    return True

for i in range(a, b + 1):
    if prime(i):
        li_1.append(i)

for i in range(c, d + 1):
    if prime(i):
        li_2.append(i)

for i in li_1:
    if i in li_2:
        li_dup.append(i)

bol = True #True면 용태가 부를 차례

while True:
    if len(li_dup) > 0:
        a = li_dup.pop()
        li_1.remove(a)
        li_2.remove(a)
        bol = not(bol)
    else:
        if bol:
            if len(li_1) == 0:
                print('yj')
                break
            li_1.pop()
            bol = not(bol)
        else:
            if len(li_2) == 0:
                print('yt')
                break
            li_2.pop()
            bol = not(bol)