# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
button = list(map(float, input().split()))
first_number = True
cnt = 0

def check_decimal(x):
    if x % 1 == 0:
        return False
    else:
        return True

for i in button:
    if check_decimal(i):
        if not(first_number):
            cnt += int(i // 1)
        else:
            cnt += int(i // 1) + 1
    else:
        cnt += int(i // 1)

    if i == 0:
        continue
    else:
        first_number = False
print(cnt)