# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
sum_li = [0] * 100000
sum_li[0] = li[0]

for i in range(1, len(li)):
    sum_li[i] = max(sum_li[i - 1], 0) + li[i]

print(max(sum_li))