# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, m = map(int, input().split())
A = []
B = []

for _ in range(n):
    A.append(list(map(int, input().split())))

m, k = map(int, input().split())
for _ in range(m):
    B.append(list(map(int, input().split())))

ans = [[0 for _ in range(k)] for _ in range(n)]


for b in range(n):
    for c in range(k):
        val = 0
        for a in range(m):
            val += A[b][a] * B[a][c]
        ans[b][c] = val

for i in range(len(ans)):
    print(*ans[i])