# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a = int(input())
b = int(input())
c = int(input())
res = a * b * c
dic = {'0' : 0, '1' : 0, '2' : 0, '3' : 0, '4' : 0, '5' : 0, '6' : 0, '7' : 0,
       '8' : 0, '9' : 0}

for i in str(res):
    dic[i] += 1

for i in dic:
    print(dic[i])