# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
cnt = 0
li = []

def test(x):
    for i in range(len(li)):
        st = 0
        ba = 0
        for j in range(3):
            if x[j] == li[i][0][j]:
                st += 1
            elif li[i][0].find(x[j]) != -1:
                ba += 1
        if li[i][1] == st and li[i][2] == ba:
            continue
        else:
            return False
    return True

for _ in range(n):
    li.append(list(map(int, input().split())))

for i in li:
    i[0] = str(i[0])

for i in range(123, 988):
    i = str(i)
    if i[0] != i[1] and i[0] != i[2] and i[1] != i[2] and i[1] != '0' and i[2] != '0':
        if test(i):
            cnt += 1

print(cnt)