# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

while True:
    a = int(input())
    sum = 0
    if a == 0:
        break
    a = str(a)
    a = a[::-1]
    a = int(a)
    print(a, end = ' ')
    a = str(a)
    for i in a:
        sum += int(i)
    print(sum)