# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

c = []
n = []
sc = []

for _ in range(5):
    a, b = input().split()
    c.append(a)
    b = int(b)
    n.append(b)


n.sort()

def getsocre():
    global sc
    if c[0] == c[1] == c[2] == c[3] == c[4]:
        sc.append(max(n) + 600) #4번
        pre = n[0]
        combo = 0
        for i in range(1, 5):
            if pre + 1 == n[i]:
                pre = n[i]
                combo += 1
        if combo == 4:
            sc.append(max(n) + 900) #1번

    if n[0] == n[3]:
        sc.append(n[0] + 800)
    if n[1] == n[4]:
        sc.append(n[1] + 800) #2번

    if n[0] == n[2] and n[3] == n[4]:
        sc.append(n[0] * 10 + n[3] + 700)
    if n[0] == n[1] and n[2] == n[4]:
        sc.append(n[2] * 10 + n[0] + 700) #3번

    pre = n[0]
    combo = 0
    for i in range(1, 5):
        if pre + 1 == n[i]:
            pre = n[i]
            combo += 1
        if combo == 4:
            sc.append(max(n) + 500) #5번

    if n[0] == n[2]:
        sc.append(n[0] + 400)
    if n[2] == n[4]:
        sc.append(n[2] + 400) #6번

    if n[0] == n[1] and n[2] == n[3]:
        sc.append(max(n[0], n[2]) * 10 + min(n[0], n[2]) + 300)
    if n[0] == n[1] and n[3] == n[4]:
        sc.append(max(n[0], n[3]) * 10 + min(n[0], n[3]) + 300)
    if n[1] == n[2] and n[3] == n[4]:
        sc.append(max(n[1], n[3]) * 10 + min(n[1], n[3]) + 300) #7번

    if n[0] == n[1]:
        sc.append(n[0] + 200)
    if n[1] == n[2]:
        sc.append(n[1] + 200)
    if n[2] == n[3]:
        sc.append(n[2] + 200)
    if n[3] == n[4]:
        sc.append(n[3] + 200) #8번
    return sc

getsocre()
if len(sc) == 0:
    sc.append(max(n) + 100) #9번

print(max(sc))