# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

graph = [[False] * 100 for i in range(100)]
l = 0
r = [1, -1, 0, 0]
c = [0, 0, 1, -1]

def check(x, y):
    global l
    for i in range(4):
        if graph[x][y] == True:
            if x + r[i] >= 100 or x + r[i] < 0 or y + c[i] >= 100 or y + c[i] < 0:
                l += 1
                continue
            if graph[x + r[i]][y + c[i]] == False:
                l += 1

n = int(input())
for i in range(n):
    x, y = map(int, input().split())
    for i in range(y, y + 10):
        for j in range(x, x + 10):
            graph[i][j] = True

for i in range(100):
    for j in range(100):
        check(i, j)

print(l)