# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
li.sort()
maxi = 0
if len(li) % 2 == 0:
    for i in range(len(li) // 2):
        maxi = max(maxi, li[i] + li[len(li) - 1 - i])

if len(li) % 2 == 1:
    for i in range(len(li) // 2):
        maxi = max(maxi, li[i] + li[len(li) - 2 - i])
    maxi = max(maxi, li[len(li) - 1])

print(maxi)