# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
dp = [0] * (n + 1)

if n >= 2:
    dp[2] = 1
if n >= 3:
    dp[3] = 2
    for i in range(3, n +1):
        if i % 6 == 0:
            dp[i] = min(dp[i - 1] + 1, dp[int(i / 3)] + 1, dp[int(i / 2)] + 1)
        elif i % 3 == 0:
            dp[i] = min(dp[i - 1] + 1,dp[int(i / 3)] + 1)
        elif i % 2 == 0:
            dp[i] = min(dp[i - 1] + 1, dp[int(i / 2)] + 1)
        else:
            dp[i] = dp[i - 1] + 1
print(dp[n])