# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys

n = int(sys.stdin.readline())
li = []
sum = 0
def my_round(a):
    if a % 1 < 0.5:
        return int(a)
    else:
        return int(a) + 1

for _ in range(n):
    a = int(sys.stdin.readline())
    li.append(a)
    sum += a

aver = my_round(n * 0.15)

if n == 0:
    print(0)

elif aver < 0.5:
    print(my_round(sum / n))

else:
    li.sort()
    li = li[aver: n - aver]

    sum = 0
    for i in li:
        sum += i
    b = sum / len(li)
    print(my_round(b))