# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
dp = [0] * (n + 1)
dp2 = [0] * (n + 1)
dp[0] = 3
dp2[0] = 2
dp[1] = 7
dp2[1] = 5

if n >= 3:
    for i in range(2, n + 1):
        dp[i] = dp[i - 1] + 2 * dp2[i - 1]
        dp2[i] = dp[i - 1] + dp2[i - 1]

print(dp[n - 1] % 9901)