# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

N = int(input())
A = list(map(int, input().split()))

dp = [1] * N #이 dp는 수열의 길이를 담음, 수열의 길이는 최소가 1이므로 초기값을 1로 설정

for i in range(1, N):
    for j in range(i):#수열의 i 인덱스 수는 i 인덱수 수보다 더 먼저 나온 수들과 수열을 만들어야 되기 때문에 range(i)를 사용
        if A[i] > A[j]: #수열의 i 인덱스 수와 그보다 먼저 나온 수들을 비교
            dp[i] = max(dp[i], dp[j]+1) #만약 A[i]가 A[j]보다 크다면 dp[j] 수열에 A[i]를 붙여서 수열의 길이를 하나 늘릴 수 있으므로 dp[j] + 1, max를 해서 비교하는 이유는 가장 마지막 dp[j] = [3, 1]일 경우, 1보다 이전인 3일때가 최대이기 때문에 max를 해서 비교한다

print(max(dp))