# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
m = int(input())
li = []
vi = [1]

for _ in range(m):
    li.append(list(map(int, input().split())))

def find():
    global vi
    pre_vi = vi
    for i in li:
        if i[0] in vi:
            vi.append(i[1])
    vi = set(vi)
    vi = list(vi)
    vi.sort()
    if vi == pre_vi:
        return len(vi)
    find()

print(find())