# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
m = int(input())

sum1 = 0
sum2 = 0

for i in li:
    if m % i == 0:
        sum1 += i

for i in li:
    if i % m == 0:
        sum2 += i

print(sum1)
print(sum2)