# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
score = []
dp = [0] * (n + 1)
for _ in range(n):
    score.append(int(input()))

if n >= 1:
    dp[1] = score[0]

if n >= 2:
    dp[2] = score[0] + score[1]

if n >= 3:
    dp[3] = max(dp[1] + score[2], score[1] + score[2])

if n >= 4:
    for i in range(4, n + 1):
        dp[i] = max(dp[i - 3] + score[i - 2] + score[i -1], dp[i - 2] + score[i - 1])

print(dp[n])