# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

t = int(input())
for _ in range(t):
    n = int(input())
    dp = [0] * (n + 1)
    if n >= 1:
        dp[1] = 1
    if n >= 2:
        dp[2] = 2
    if n >= 3:
        dp[3] = 4
    if n >= 4:
        for i in range(4, n + 1):
            dp[i] = dp[i -1] + dp[i - 2] + dp[i - 3]
    print(dp[n])