# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = input()
ans = ''
num1, flo = map(int, n.split('.'))

ans += str(bin(num1))[2:]
ans += '.'
num2 = float(n) - num1

while True:
    num2 *= 2
    num3, flo = map(int, str(num2).split('.'))
    num2 = float(num2) - num3
    ans += str(num3)
    if num2 == 0:
        ans += '0'
        break

ans_int, ans_flo = map(str, ans.split('.'))
final = ans_int + '.' + ans_flo[:4]
print(final)