# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, b = map(int, input().split())
dp = [0] * (b + 1)
ind = [i for i in range(30)]
A = []

for _ in range(n):
    A.append(list(map(int, input().split())))

class matrix:
    def __init__(self, li):
        self.li = li

    def __mul__(self, other):
        ans = [[0 for _ in range(n)] for _ in range(n)]
        for b in range(n):
            for c in range(n):
                val = 0
                for a in range(n):
                    val += self.li[b][a] * other.li[a][c]
                ans[b][c] = val % 1000
        return matrix(ans)

    def __pow__(self, num):
        ans = [[0 for _ in range(n)] for _ in range(n)]
        for b in range(n):
            for c in range(n):
                val = 0
                for a in range(n):
                    val += self.li[b][a] * self.li[a][c]
                ans[b][c] = val % 1000
        return matrix(ans)

    def __str__(self):
        return str(self.li)

A = matrix(A)

A2 = A ** 2
A2 = matrix(A2)

dp[1] = A
dp[2] = A2

for i in range(1, b + 1):
    if i >= 3:
        for j in ind:
            if i == 2 ** j:
                dp[i] = dp[i // 2] * dp[i // 2]
                dp[i] = matrix(dp[i])

val = bin(b)
val = val[2:]
val = val[::-1]
base = [[0 for i in range(n)] for i in range(n)]

for i in range(n):
        base[i][i] = 1

base = matrix(base)

for i in range(len(val)):
    if val[i] == '1':
        base =  base * dp[2 ** i]
        base = matrix(base)

for i in base.li:
    print(*i)