# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
m = int(input())
fix = []
dp = [0] * (n + 1)
dp[0] = 1
dp[1] = 2
st = ''
cnt = 1

for _ in range(m):
    fix.append(int(input())) #고정석 확인

for i in range(n):
    if i + 1 in fix:
        st += '1' #고정석를 1로 설정해서 고정석 단위로 끊어서 확인 가능하도록 함
    else:
        st += '0'

if n > 2:
    for i in range(2, n):
        dp[i] = dp[i - 1] + dp[i - 2]

st_li = st.split('1')
for i in st_li:
    if len(i) == 0:
        continue
    cnt *= dp[len(i) - 1]

print(cnt)