# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

t = int(input())
li = []
li_2 = []
for _ in range(t):
    li.append(input())
    a = int(input())
    li_2.append(input())

for i in li:
    work(i)
    for j in range(len(i)):
        if i[j] == 'R':
            remo(i)
        elif i[j] == 'D':
            rever(i)

def work(a):
    if len(a)
    if a[0] == 'R':

        work(a[1:])



def remo(li):
    if len(li) == 0:
        return 'error'
    else:
        li = li[1:]
        return li

def rever(li):
    li = li[::-1]
    return li