# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

m, n = map(int, input().split())
num_li = [False, False] + [True] * (n - 1)
prime_li = []
ans = []

for i in range(2, n + 1):
    if num_li[i]:
        prime_li.append(i)
        for i in range(2 * i, n + 1, i):
            num_li[i] = False

for i in prime_li:
    if i >= m:
        ans.append(i)

print(len(ans))