# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

a = input()
cnt1 = 0
cnt2 = 0

for i in range(len(a) - 2):
    if a[i] == 'K':
        if a[i + 1: i + 3] == 'OI':
            cnt1 += 1

    elif a[i] == 'I':
        if a[i + 1: i + 3] == 'OI':
            cnt2 += 1

print(cnt1)
print(cnt2)