# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

st = input()
sum = 0
if not '-' in st:
    st = st.split('+')
    for i in st:
        sum += int(i)

else:
    st = st.split('-')
    sub = 0

    for i in range(len(st)):
        st[i] = st[i].split('+')

    for i in range(1, len(st)):
        for j in range(len(st[i])):
            sub += int(st[i][j])

    for i in range(len(st[0])):
        sum += int(st[0][i])

    sum = sum - sub

print(sum)