# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import math
n = int(input())
li = []

for i in range(n):
    li.append(int(input()))

def isprime(x):
    if x <= 1:
        return False
    for i in range(2, math.isqrt(x) + 1):
        if x % i == 0:
            return False
    return True

for i in li:
    if isprime(i):
        print(i)
    else:
        d = 1
        while not (isprime(i-d) or isprime(i+d)):
            d += 1
        if isprime(i - d):
            print(i - d, end=' ')
        if isprime(i + d):
            print(i + d, end=' ')
        print()