# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, k = map(int, input().split())

dp = [[1] * (k + 1) for _ in range(n + 1)] #DP 테이블을 만들 때 0 ~ N까지의 수를 만드는 경우는 기본적으로 1가지, 1개만큼 더하는 경우, 2개만큼 더하는 경우... k개만큼 더하는 경우가 모두 존재하므로 이를 이차원 리스트로 표현함, 원래 *k가 맞지만 인덱싱할때의 가독성을 위해 *(k + 1)로 표현
for i in range(2, k + 1):
    for j in range(1, n + 1):
        dp[j][i] = (dp[j - 1][i] + dp[j][i - 1]) % 1000000000

print(dp[n][k])