# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import collections
pizza = [collections.deque() for _ in range(51)]
price = [collections.deque() for _ in range(51)]

p, n = map(int, input().split())
ans = 0
for _ in range(n):
    info = list(map(int, input().split()))
    if info[0] == 0:
            pizza[info[1]].append(1)
            price[info[1]].append(info[2])
    if info[0] == 1:
        if len(pizza[info[1]]) != 0:
            pizza[info[1]].popleft()
            a = price[info[1]].popleft()
            ans += a
        else:
            continue
print(ans)