# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

graph = [[False] * 100 for i in range(100)]
cnt = 0

n = int(input())
for i in range(n):
    x, y = map(int, input().split())
    for i in range(x, x + 10):
        for j in range(y, y + 10):
            graph[i][j] = True

for i in graph:
    for j in i:
        if j == True:
            cnt += 1

print(cnt)