# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

T = int(input())  # 목표 금액
k = int(input())  # 동전 종류 개수
coins = []
for _ in range(k):
    coins.append(list(map(int, input().split())))  #동전 금액과 가치 한 리스트에 입력 받아서 이차원 리스트 만듦

result = [0] * (T + 1) #DP 테이블 초기화(0부터 T까지의 금액을 만드는 방법을 저장)
result[0] = 1  #0원을 만드는 방법은 1개이므로 초기값 배정

for p, n in coins:
    for t in range(T, p - 1, -1):
        #동전 T를 만들 수 있는 방법을 역순으로 탐색(역순으로 탐색하는 이유는)
        for i in range(1, min(n, t // p) + 1):
            '''t // p는 금액 t를 만드는데 사용할 수 있는 동전 p의 최대 개수이다 n개가 존재하는데 그보다 더 많이 동전을 사용해선 안 되고, 이미 금액을 완성했는데도 동전을 더 사용하면 안 되니 min(n, t // p)를 사용해서
            둘 중 더 작은 값을 사용하는 코드를 짬'''
            result[t] += result[t - p * i]
            #t 금액은 t - p * i 금액에서 p 금액의 동전을 i개 사용하면 완성할 수 있으므로 result[t - p * i]를 만드는 개수를 더해준다


print(result[T])