# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

d, k = map(int, input().split())
dd = [[0] for i in range(31)]
dd[d] = k

for i in range(1, k + 1):
    dd[d - 1] = i
    for j in range(2, d):
        dd[d - j] = dd[d - j + 2] - dd[d - j + 1]

    if dd[1] > 0 and dd[2] > 0 and dd[1] < dd[2]:
        print(dd[1])
        print(dd[2])
        break