# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
first_li = list(map(int, input().split()))
grow_li = list(map(int, input().split()))
wood = 0

for i in range(n):
    a = min(grow_li)
    wood += first_li[grow_li.index(a)]
    first_li[grow_li.index(a)] = 0
    first_li.pop(grow_li.index(a))
    grow_li.remove(a)
    for j in range(len(grow_li)):
        first_li[j] += grow_li[j]

print(wood)