# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

m = int(input())
li = list(map(str, input().split()))

while True:
    if len(li) < 3:
        break
    for i in range(2, len(li)):
        if li[i] == '+':
            value = int(li[i - 2]) + int(li[i - 1])
            li[i] = value
            li.remove(li[i - 1])
            li.remove(li[i - 2])
            break
        if li[i] == '-':
            value = int(li[i - 2]) - int(li[i - 1])
            li[i] = value
            li.remove(li[i - 1])
            li.remove(li[i - 2])
            break
        if li[i] == '*':
            value = int(li[i - 2]) * int(li[i - 1])
            li[i] = value
            li.remove(li[i - 1])
            li.remove(li[i - 2])
            break
        if li[i] == '/':
            value = int(int(li[i - 2]) / int(li[i - 1]))
            li[i] = value
            li.remove(li[i - 1])
            li.remove(li[i - 2])
            break


print(*li)