# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

N = int(input())
li = list(map(int, input().split()))
dp = [0] * N #DP 테이블 생성

dp[0] = li[0]

for i in range(N):
    for j in range(i):
        if li[i] > li[j]:
            dp[i] = max(dp[i], dp[j] + li[i])
        else:
        	dp[i] = max(dp[i], li[i])

print(max(dp))