# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, s, m = map(int, input().split())
v = list(map(int, input().split()))
dp = [[0] * (m + 1) for _ in range(n + 1)]
dp[0][s] = 1
cnt = 0

for i in range(1, n + 1):
    for j in range(0, m + 1):
        if dp[i - 1][j] == 1:
            if 0 <= j + v[i - 1] <= m:
                dp[i][j + v[i - 1]] = 1
            if 0 <= j - v[i - 1] <= m:
                dp[i][j - v[i - 1]] = 1
    if not(1 in dp[i]):
        print(-1)
        cnt += 1
        break

if cnt == 0:
    for i in range(len(dp[n])):
        if dp[n][i] == 1:
            max = i
    print(max)