# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import collections
deck = collections.deque()

n = int(input())
for i in range(1, n + 1):
    deck.append(i)
player = []

for i in range(n):
    a = deck.popleft()
    player.append(a)
    if len(deck) == 0:
        break
    b = deck.popleft()
    deck.append(b)

print(*player)