# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
stack = []
for _ in range(n):
    a = list(map(str, input().split()))
    if a[0] == 'i':
        stack.append(int(a[1]))
    if a[0] == 'c':
        print(len(stack))
    if a[0] == 'o':
        if len(stack) == 0:
            print('empty')
        else:
            print(stack[len(stack) - 1])
            stack.pop()