# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, m = map(int, input().split())
val = [0 for _ in range(n)]

def dice(step):
    if step >= n:
        sum = 0
        for i in val:
            sum += i
        if sum == m:
            print(*val)
        return

    for i in range(1, 7):
        val[step] = i
        dice(step + 1)

dice(0)