# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

m = int(input())
n = int(input())
prime_li = []

def prime(x):
    if x == 1:
        return False

    for i in range(2, x):
        if x % i == 0:
            return False
    return True

for i in range(m, n + 1):
    if prime(i):
        prime_li.append(i)

sum = 0
for i in prime_li:
    sum += i

if sum == 0:
    print(-1)

else:
    print(sum)
    print(prime_li[0])