# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import collections
q = collections.deque()

n = int(input())
for _ in range(n):
    a = list(map(str, input().split()))
    if a[0] == 'i':
        q.append(a[1])
    if a[0] == 'c':
        print(len(q))
    if a[0] == 'o':
        if len(q) == 0:
            print('empty')
        else:
            print(q.popleft())