# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n , k = map(int, input().split())
li = []

for i in range(1, n + 1):
    if n % i == 0:
        li.append(i)

if len(li) < k:
    print(0)
else:
    print(li[k - 1])