# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
new_li = []
new_li.append(li[0])
li = li[1:]

while True:
    if len(li) == 0:
        break
    new_li.append(li[0])
    li = li[1:]
    new_li.sort()
    print(*new_li, *li)