# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
move = []
ball = input()

R = ball.count('R')
B = ball.count('B')
LR = (ball+'B').find('B')
LB = (ball+'R').find('R')

move.append(R - LR)
move.append(B - LB)

ball = ball[::-1]
RR = (ball+'B').find('B')
RB = (ball+'R').find('R')

move.append(R - RR)
move.append(B - RB)

print(min(move))