# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys
n, m = map(int, input().split())
dic_pocket = {}
dic_num = {}

for i in range(1, n + 1):
    name = input()
    dic_pocket[str(i)] = name
    dic_num[name] = i

for i in range(m):
    a = input()
    if dic_pocket.get(a) != None:
            print(dic_pocket[a])
    else:
        print(dic_num[a])