# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
dic = {}
n_li = list(map(str, input().split()))

for i in n_li:
    dic[i] = True

m = int(input())
m_li = list(map(str, input().split()))

for i in m_li:
    if dic.get(i) == True:
        print(1)
    else:
        print(0)