# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

from math import sqrt
n = int(input())
dp = [0] * (n + 1) #DP 테이블 생성

for i in range(1, n + 1):
    dp[i] = i #초기값은 모든 값들을 1로 몇 번 나눌 수 있냐로 설정

for i in range(n + 1):
    for j in range(1, int(sqrt(i)) + 1): #각 수를 제곱수로 나눌 수 있는 모든 경우를 생각
        dp[i] = min(dp[i], dp[i - j ** 2] + 1) #제곱수로 나눈 경우, ex. 11 = 3^2 + 2는 dp[2] + 1을 하면 되므로 이처럼 코드를

print(dp[n])