# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import math

def isprime(x):
    for i in range(2, math.isqrt(x) + 1):
        if x % i == 0:
            return False
    return True

li = list(map(int, input().split()))
for i in li:
    if i == 1:
        print('number one')
    else:
        if isprime(i):
            print('prime number')
        else:
            print('composite number')