# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
dp = []

for i in range(n):
    if min(li) in dp:
        li.remove(min(li))
    else:
        dp.append(min(li))
        li.remove(min(li))

print(len(dp))