# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = []
ans = 0
for _ in range(n):
    a, b = map(int, input().split())
    li.append([a, b])

graph = [[0] * 100 for _ in range(100)]

for i in range(len(li)):
    left, under = li[i]
    for i in range(10):
        for j in range(10):
            graph[left + i][under + j] = 1

for i in graph:
    for j in i:
        if j == 1:
            ans += 1
print(ans)