# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
p = list(map(int, input().split()))
time = 0
p.sort()

for i in range(len(p)):
    time += p[i] * (len(p) - i)

print(time)