# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

import sys
n, m = map(int, sys.stdin.readline().strip().split())
li_1 = []
li_2 = []

for i in range(n):
    li_1.append(sys.stdin.readline().strip())
for j in range(m):
    li_2.append(sys.stdin.readline().strip())

li_1 = set(li_1)
li_2 = set(li_2)

new_set = set.intersection(li_1, li_2)
new_set = sorted(new_set)
print(len(new_set))
for i in new_set:
    print(i)

n = int(input())
p = int(input())

if n < 5:
    print(p)
elif n < 10:
    a = p - 500
    if a < 0:
        print(0)
    else:
        print(a)
elif n < 15:
    a = min(p - 500, int(p / 100 * 90))
    if a <= 0:
        print(0)
    else:
        print(a)
elif n < 20:
    a = min(p - 500, int(p / 100 * 90), p - 2000)
    if a <= 0:
        print(0)
    else:
        print(a)
else:
    a = min(p - 500, int(p / 100 * 90), p - 2000, int(p / 100 * 75))
    if a <= 0:
        print(0)
    else:
        print(a)