# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
li = list(map(int, input().split()))
new_li = []

for i in range(n - 1):
    for i in range(len(li) - 1):
        if li[i] > li[i + 1]:
            li[i], li[i+1] = li[i+1], li[i]
    new_li.append(li[len(li) - 1])
    li = li[:len(li) - 1]
    print(*li, *new_li[::-1])