# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
dp = [0] * (n + 1)
if n >= 2:
    dp[2] = 3
if n >= 4:
    for i in range(4, n + 1):
        if i % 2 == 0:
            dp[i] += 2
            dp[i] += dp[i - 2] * 3
            for j in range(4, i, 2):
                dp[i] += 2 * dp[i - j]
        else:
            dp[i] = 0
print(dp[n])