# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

l, u = map(int, input().split())

def add(x):
    adding = 0
    digit = 1

    while x > 0:
        adding += x
    return adding

print(add(u) - add(l - 1))

def digit_sum_up_to(x):
    if x < 0:
        return 0

    adding = 0
    factor = 1

    while x // factor > 0: #현재 자리수까지만 계산하기 위함
        lower_digits = x % factor
        current_digit = (x // factor) % 10
        higher_digits = x // (factor * 10)

        # 각 자릿수의 합을 계산
        adding += higher_digits * factor * 45  #만약 입력받은 수가 47이라면 두번째 자리수가 0, 1, 2, 3일 때, 총 4번 45가 더해졌으므로 앞과 같은 식이 나온다
        adding += current_digit * (lower_digits + 1)
        adding += (current_digit * (current_digit - 1)) // 2 * factor

        factor *= 10

    return adding

l, u = map(int, input().split())

print(digit_sum_up_to(u) - digit_sum_up_to(l - 1))