# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

li = [input() for _ in range(5)]
ans = ''

for i in range(15):
    for j in range(5):
        if i > len(li[j]) - 1:
            continue
        ans += li[j][i]

print(ans)