# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

k = int(input())
li = []
sub_li = []
max = 0
rect1 = 0
rect2 = 0
ind = 0

for _ in range(6):
    li.append(list(map(int, input().split())))

for i in range(len(li)):
    if max < li[i][1]:
        max = li[i][1]
        ind = i

rect1 = li[ind - 1][1] * li[ind - 2][1]
rect2 = li[ind - 4][1] * li[ind - 5][1]

print((rect1 + rect2) * k)