# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n, b = map(int, input().split())

if b == 2:
    ans = str(bin(n)).upper()
    print(ans[2:])
if b == 8:
    ans = str(oct(n)).upper()
    print(ans[2:])
if b == 16:
    ans = str(hex(n)).upper()
    print(ans[2:])

#진법 변환(정올 사이트)
def change(x, y):
    if x // y >= 1:
        change(x // y, y)
    return print(alp[x % y], end = '')

while True:
    user = input()
    if user == '0':
        break
    a, s, b = map(str, user.split())
    a = int(a)
    b = int(b)
    li = []
    num = 0
    alp = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

    #10진수로 변환
    if a > 10:
        for i in range(len(s)):
            num += int(alp.find(s[len(s) - i - 1])) * a ** i

    else:
        for i in range(len(s)):
            num += int(s[len(s) - i - 1]) * a ** i

    change(num, b)
    print()