# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

n = int(input())
first_li = list(map(int, input().split()))
grow_li = list(map(int, input().split()))

# 성장률과 처음 나무의 길이를 함께 묶어서 성장률 기준으로 정렬
trees = sorted(zip(grow_li, first_li))

wood = 0
for i in range(n):
    # 현재 남은 나무의 길이 계산 (나무 성장량 * 날 수)
    grow, initial = trees[i]
    wood += initial + grow * i

print(wood)