# -*- coding: utf-8 -*-
"""abcd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWT2kTx_yGZgG4qQUHVvAN1QupY_6hh_
"""

while True:
    dic = {}
    a = input()
    if a == 'END':
        break
    li = list(map(str, a.split()))
    for i in li:
        if i in dic:
            continue
        else:
            dic[i] = 0

    for i in li:
        dic[i] += 1

    key = sorted(dic)

    for i in key:
        print(f'{i} : {dic.get(i)}')